<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Dawnsbury.Mods.RemasterExpanded</AssemblyName>
    <Platforms>x64</Platforms>
    <NoWarn>1998;NETSDK1206;NU1901;NU1902;NU1903;NU1904;VSTHRD200; CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Common">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Common.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury Days">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Dawnsbury Days.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.DawnniExpanded">
      <HintPath>D:\SteamLibrary\steamapps\workshop\content\2693730\3163146733\CustomMods\Dawnsbury.Mods.DawnniExpanded.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.LoresAndWeaknesses">
      <HintPath>D:\SteamLibrary\steamapps\workshop\content\2693730\3710730920\CustomModsV3\Dawnsbury.Mods.LoresAndWeaknesses.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.Remaster.FeatsDb">
      <HintPath>D:\SteamLibrary\steamapps\workshop\content\2693730\3223870401\CustomMods\Dawnsbury.Mods.Remaster.FeatsDb.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.Remaster.Spellbook">
      <HintPath>D:\SteamLibrary\steamapps\workshop\content\2693730\3223762737\CustomMods\Dawnsbury.Mods.Remaster.Spellbook.dll</HintPath>
    </Reference>
    <Reference Include="ExplorationActivities">
      <HintPath>..\..\Debug\ExplorationActivities\bin\Release\net10.0-windows\ExplorationActivities.dll</HintPath>
    </Reference>
    <Reference Include="HereThereBeDragons">
      <HintPath>..\..\HereThereBeDragons2\bin\Debug\net10.0-windows\HereThereBeDragons.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="PsychicExpanded">
      <HintPath>..\..\ClassLibrary1\PsychicExpanded\bin\Release\net10.0-windows\PsychicExpanded.dll</HintPath>
    </Reference>
    <Reference Include="SpellsAndSpellhearts">
      <HintPath>C:\Users\jcbco\RiderProjects\SpellsAndSpellhearts\SpellsAndSpellhearts\bin\Release\net10.0-windows\SpellsAndSpellhearts.dll</HintPath>
    </Reference>
    <Reference Include="SpiritDamage">
      <HintPath>..\..\SpiritDamage\SpiritDamage\bin\Debug\net10.0-windows\SpiritDamage.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="obj\DawnniExPatchMod.csproj.nuget.dgspec.json" />
    <Content Include="obj\DawnniExPatchMod.csproj.nuget.g.props" />
    <Content Include="obj\DawnniExPatchMod.csproj.nuget.g.targets" />
    <Content Include="obj\Debug\net10.0-windows\Dawnsbury.Mods.RemasterExpanded.dll" />
    <Content Include="obj\Debug\net10.0-windows\Dawnsbury.Mods.RemasterExpanded.pdb" />
    <Content Include="obj\Debug\net10.0-windows\Remaster.0EF15A91.Up2Date" />
    <Content Include="obj\Debug\net10.0-windows\RemasterExpanded.AssemblyInfoInputs.cache" />
    <Content Include="obj\Debug\net10.0-windows\RemasterExpanded.assets.cache" />
    <Content Include="obj\Debug\net10.0-windows\RemasterExpanded.csproj.AssemblyReference.cache" />
    <Content Include="obj\Debug\net10.0-windows\RemasterExpanded.csproj.CoreCompileInputs.cache" />
    <Content Include="obj\Debug\net10.0-windows\RemasterExpanded.csproj.FileListAbsolute.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\project.nuget.cache" />
    <Content Include="obj\project.packagespec.json" />
    <Content Include="obj\RemasterExpanded.csproj.nuget.dgspec.json" />
    <Content Include="obj\RemasterExpanded.csproj.nuget.g.props" />
    <Content Include="obj\RemasterExpanded.csproj.nuget.g.targets" />
    <Content Include="obj\rider.project.model.nuget.info" />
    <Content Include="obj\rider.project.restore.info" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0-windows\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
  </ItemGroup>

</Project>
